source 'https://rubygems.org'

ruby '2.1.5'

gem 'rails', '~> 4.2.0'

group :development, :test do
  gem 'sqlite3'
end

group :production do
  # gem 'pg'
end

gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'spring',        group: :development

gem 'active_model_serializers', '~> 0.8.0'

gem 'knock', '~> 1.2'

gem 'rack-cors', :require => 'rack/cors'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

